import './vendors/methods'
import './customers/methods'
import './users/server'
// import './branch/methods'
import './departments/methods'
import './position/methods'
import './employee_type/methods'
import './employee/methods'
import './branches/server'
import './attendance/methods'
import './leave/methods'
// import './notifications/methods'
import './notifications/server'

